### ISSUE TITLE
Carver's Bugfix TODO list

### ISSUE THREAD

**Issue by Pabilo8** [Pabilo8/ImmersiveIntelligence#119]
Issues to fix: 
- [x] Binocular tripod getting stuck on zooming, inability to un-zoom or leave the tripod via shift (holds player in place and displays weapon zoom akin to railgun) until world is reloaded or player rejoins.
- [x] Fix Nuke particles. So far, only shockwave and orange particles are seen. 
- [x] Fix bugs in TXT files. 2-4 total. (-1 related to scape and run, 2-3 left)
- [x] Fix Navy mine resetting it's chain lenght.
- [x] Fix tripwire mines not working AND FINALLY ADD A STICK TO ATTACH IT TO. 
- [x] Add Y level limiter option to Emplacements weapons to prevent them firing downwards undergroud. Limiter is enabled by default, but will be turned off by data if one wishes to.
- [x] Fix Emplacements not showing the IF meter/bar. Fix it not showing certain emplacements.
- [x] Change artillery Hans AI to have Y limitation, only perform attacks on targets which have been either marked or sighted. Or change it, reminder of your words: "yes, howi uses a separate targeting system, because I didn't know much about tasks then ^^
I'll change it"
- [x] Make squids not trigger navy mines or make them avoid navy mines.
- [x] Make the boat from thebetweenlands explode on navy mine.
- [x] Fix not being able to exit the MG zoom mode.
- [x] Fix mine detector render and functions.
- [x] Arm-up timer for navy mines to prevent blowing yourself up in boats.

Issues to replicate and test:
- [x] Rendering glitch with grass, all rendering glitches which cause things to go either white or like in pics. If it is all stable, then I'll re-install the client completely. 
- [x] Fixing bug, where armor and all wearabled in general from II does not render itself on PLAYER if VMW is installed. Happens only if it is equipped on players. It renders on anything else.
- [x] Projectiles being on fire, as well as navy mines.
- [x] GL ERROR - 1281: Invalid value, post render.
IMPROVE/FINISH:
- [x] Give flamethrower emplacement ability to ignite liquids, and give it sounds.
- [x] Make FLAK/autocannon animate it's guns only in tact with the firing.
- [x] Add bullet inventory to the emplacements, bullet consumption and etc. 
- [x] Finish building animation for emplacement's weapons.
- [x] Add emplacement option to not ignore walls, making it not fire behind a wall until target is seen. Off by default.
- [x] Hans team colours, made by applying render layers.
- [x] Make proper targeting list, config GUI and etc for the emplacement to make it more configurable in terms of targets. Could be modified thru the data system as well.
- [x] ADD THE STAKE FOR THE TRIPWIRE MINE TO NOT REQUIRE A SECOND MINE.
- [x] Add a special wire for the tripmines to ignore grass and other plants when placing.
- [x] Add back the regular pressure landmines.
- [x] Add the rest of the emplacements and machines planned, and finish them before moving to the new stuff.

To improve (secondary): 
- [x] improve manual entries and text overall. Requires: text sent to me and limits on the text. As well as technical data about required things.
- [x] White phosphorus igniting stuff. White clouds should either ignite everything on fire as well as applying the effects, or the greande (For example) automatically igniting everything. Or more random WP sparkles which have more velocity and randomnless to fly.
- [x] Any nuke should decimate leaves and do basic heat damage at the source. But most likely related to actual ordinance used instead of just commands.
